audit_header: false
title: "Northshore's Best Real Estate Training"
description: Mike Quail, a top Real Estate Agent in Northshore, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: https://www.eventbrite.com/e/102109163256
  - title: Free Strategy Call
    url: /strategy-call/
client:
  name: Mike Quail
  title:
  license_number:
  about_markdown: |
    Mike Quail is a Real Estate Agent at eXp Realty and founder of Mike Quail Home Selling Team. Mike and his team strive to provide clients with exceptionally competent service, to create caring relationships with clients, co-workers, and vendors, and to cultivate continual growth in their company, community, personal and professional lives, and in the lives of their clients. Mike Quail Home Selling Team also seeks to be a pillar in the local community by partnering with other local business and organizations to continually better their area. Mike Quail is a member of the Platinum Real Estate group, a group of the top 1% of agents in North America. He was named to the RE/MAX Hall of Fame several years ago and was a top producer at his previous brokerage, EXIT Realty. Mike's listings, on average, sell three times faster than other listings in Massachusetts, and he sells listings at 4.4% more than the Realtor's Board Average. Mike graduated from Babson College with a degree in Marketing, and continues to specialize in internet marketing and marketing strategy for his clients. Every three months, Mike meets with other top agents across North America to brainstorm new buyer and seller strategies. Mike lives in Danvers with his wife, Anny, and three daughters! When Mike is not working, he spends most of his time participating in activities that revolve around Barbie princesses with his daughters or playing intense Basketball games at the Beverly YMCA.
  market: Northshore
  brand: Mike Quail Home Selling Team
  brokerage:
  address: 100 Conifer Hill Road Suite 102<br>Danvers, MA. 01923
  phone: 978-406-9294
  phone_type:
  phone2:
  phone2_type:
  email: mike@thequailgroup.com
  url: http://www.soldbyquail.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Mike Quail Home Selling Team can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Northshore Real Estate Podcast with Mike Quail'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Northshore Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Mike Quail Home Selling Team - your professional Northshore Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Northshore, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Mike Quail'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Northshore Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#19489d'
  accent_color: '#bfa578'
  theme_color: '#262118'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#19489d'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
